version: 2.1

orbs:
  node: circleci/node@4.1.0
  aws-cli: circleci/aws-cli@2.0.3

jobs:
  build:
    docker:
      - image: "cimg/base:stable"
    steps:
      - node/install
      # - aws-cli/setup
      - node/install-yarn
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            # Find a cache corresponding to this specific package.json checksum
            # when this file is changed, this key will fail
            - v1-dependencies-{{ checksum "package.json" }}
            # Find the most recently generated cache used from any branch
            - v1-dependencies-
      - run: 
          name: Install Client Dependencies
          command: yarn client:install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Build Client
          command: yarn client:build
  test:
    docker:
      - image: "cimg/base:stable"
    steps:
      - node/install
      - node/install-yarn
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            # Find a cache corresponding to this specific package.json checksum
            # when this file is changed, this key will fail
            - v1-dependencies-{{ checksum "package.json" }}
            # Find the most recently generated cache used from any branch
            - v1-dependencies-
      - run: 
          name: Install Client Dependencies
          command: yarn client:install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: 
          name: Test Client 
          command: yarn client:test

workflows:
  build_test_deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      # - deploy:
      #     requires:
      #       - test